### ISSUE TITLE
Error opening leader 2

### ISSUE THREAD

**Issue by rapier1** [bitonic/pipes-speed-test#2]
I'm getting the above error when running 'write'. This is under Ubuntu 22.04.2 LTS using the 5.15.0 kernel. Any insight? I know this is related to perf_event_open() but I don't know how to debug this in this situation. 

Thanks for the great article. I'd just like to get the code running so I can see how this all comes together in more detail.

**Comment by jbd** [comment]
Hi,

have a look at https://www.kernel.org/doc/html/latest/admin-guide/perf-security.html and /proc/sys/kernel/perf_event_paranoid. You could also run the code as the root user.

**Comment by rapier1** [comment]
Thanks!
